In [23]:
import numpy as np
import pandas as pd
import pickle
import statsmodels.api as st
import statsmodels.discrete.discrete_model as sm

build function to find optimal n_estimators
note: if learning_rate, reg_alpha, reg_lambda are not set
xgboost will use default values from https://github.com/dmlc/xgboost/blob/master/doc/parameter.md
e.g. eta = 0.3 instead of 0.1
if they are set, eta, alpha, lambda will be overwritten
the best n_estimators is Name + 1

In [24]:
# load data
with open("data_processed_test.pkl", "rb") as f:
    train_data = pickle.load(f)
    train_label = pickle.load(f)
    test_data = pickle.load(f)
    test_label = pickle.load(f)
    label_list = pickle.load(f)

In [25]:
label_list

['Adoption', 'Died', 'Euthanasia', 'Return_to_owner', 'Transfer']

# Build model

In [26]:
train_data = st.add_constant(train_data, prepend = False)

In [27]:
# fit a logistic regression model to the data
model = st.MNLogit(train_label, train_data)

In [28]:
model_fit = model.fit()

/Users/hoangnguyen/miniconda3/envs/pydata/lib/python3.5/site-packages/statsmodels/discrete/discrete_model.py:580: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  start_params = np.zeros((self.K * (self.J-1)))
/Users/hoangnguyen/miniconda3/envs/pydata/lib/python3.5/site-packages/statsmodels/discrete/discrete_model.py:1840: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  params = params.reshape(self.K, -1, order='F')
/Users/hoangnguyen/miniconda3/envs/pydata/lib/python3.5/site-packages/statsmodels/discrete/discrete_model.py:1756: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  params = params.reshape(self.K, -1, order='F')


         Current function value: 0.960631
         Iterations: 35


/Users/hoangnguyen/miniconda3/envs/pydata/lib/python3.5/site-packages/statsmodels/discrete/discrete_model.py:1697: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  params = params.reshape(self.K, -1, order='F')
/Users/hoangnguyen/miniconda3/envs/pydata/lib/python3.5/site-packages/statsmodels/base/model.py:466: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)
/Users/hoangnguyen/miniconda3/envs/pydata/lib/python3.5/site-packages/statsmodels/discrete/discrete_model.py:588: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  mnfit.params = mnfit.params.reshape(self.K, -1, order='F')


In [29]:
print(model_fit.summary())

                          MNLogit Regression Results                          
Dep. Variable:            OutcomeType   No. Observations:                12399
Model:                        MNLogit   Df Residuals:                    12295
Method:                           MLE   Df Model:                          100
Date:                Tue, 29 Nov 2016   Pseudo R-squ.:                  0.2241
Time:                        01:13:01   Log-Likelihood:                -11911.
converged:                      False   LL-Null:                       -15351.
                                        LLR p-value:                     0.000
                 OutcomeType=1       coef    std err          z      P>|z|      [95.0% Conf. Int.]
--------------------------------------------------------------------------------------------------
Age                                0.9917      0.269      3.688      0.000         0.465     1.519
Size                               0.2484      0.517      0.481      0.

/Users/hoangnguyen/miniconda3/envs/pydata/lib/python3.5/site-packages/statsmodels/discrete/discrete_model.py:1697: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  params = params.reshape(self.K, -1, order='F')
/Users/hoangnguyen/miniconda3/envs/pydata/lib/python3.5/site-packages/statsmodels/discrete/discrete_model.py:580: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  start_params = np.zeros((self.K * (self.J-1)))
/Users/hoangnguyen/miniconda3/envs/pydata/lib/python3.5/site-packages/statsmodels/discrete/discrete_model.py:1840: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  params = params.reshape(self.K, -1, order='F')
/Users/hoangnguyen/miniconda3/envs/pydata/lib/python3.5/site-packages/statsmodels/discrete/discrete_model.py:1756: VisibleDeprecationWarning: using a non-integer numbe

In [ ]:
print(model_fit.aic)

In [21]:
#model1 = st.OLS(train_label, train_data).fit()

In [22]:
#print(model1.summary())

# Attributes of model

In [19]:
feat_labels = train_data.columns[0:]
feat_labels

Index(['Age', 'Size', 'HasName_0', 'HasName_1', 'TimeofDay_lateday',
       'TimeofDay_midday', 'TimeofDay_morning', 'TimeofDay_night', 'WeekDay_0',
       'WeekDay_1', 'WeekDay_2', 'WeekDay_3', 'WeekDay_4', 'WeekDay_5',
       'WeekDay_6', 'IsIntact_0.0', 'IsIntact_1.0', 'Sex_Female', 'Sex_Male',
       'MixorMultipleorSimple_Mix', 'MixorMultipleorSimple_Multiple',
       'MixorMultipleorSimple_Simple', 'Group_Herding', 'Group_Hound',
       'Group_NonSporting', 'Group_PitBull', 'Group_Sporting', 'Group_Terrier',
       'Group_Toy', 'Group_Unknown', 'Group_Working', 'IsMixColor_0',
       'IsMixColor_1'],
      dtype='object')

In [ ]:
for f in range(train_data.shape[1]):
    print("{0}. Feature {1}: {2}".format(f + 1, feat_labels[indices[f]], importances[indices[f]]))

In [7]:
print(model.coef_)

[[ -8.03299053e-01  -3.46741991e-02  -9.17044382e-02   9.17044382e-02
    3.70916571e-01  -2.23448899e-01   1.77127211e-02  -1.65180393e-01
   -1.89674149e-01  -2.06801026e-01  -7.19432760e-02  -1.56130221e-01
   -1.69464810e-01   4.80546269e-01   3.13467212e-01   1.48727722e+00
   -1.48727722e+00   1.09321922e-01  -1.09321922e-01   1.16359785e-02
    1.56925681e-01  -1.68561659e-01   1.55763664e-01   2.45563290e-01
    6.84991574e-03  -5.73841238e-01  -9.55426408e-03   3.78070197e-01
    1.66517381e-02   2.41936859e-03  -2.21922671e-01  -3.38628984e-02
    3.38628984e-02]
 [  1.50307926e-01   1.34287508e-01   7.28729249e-01  -7.28729249e-01
   -5.55147487e-01  -3.03207611e-01   4.97181069e-01   3.61174028e-01
    3.11827113e-01   1.69778513e-01  -4.93215708e-01  -2.58177210e-01
    5.89200797e-02   3.48876473e-02   1.75979566e-01  -6.13850552e-01
    6.13850552e-01   9.91274988e-03  -9.91274989e-03  -3.48498261e-02
    6.30300837e-04   3.42195252e-02  -1.97826966e-01  -1.71573788e-01


In [22]:
print(model.intercept_)

[ 1.21763285 -2.86396309 -0.74538949 -0.08371984  2.47543957]


# Make prediction

In [8]:
predict_label = model.predict(test_data)

In [ ]:
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

In [9]:
predict_label

array([4, 4, 0, ..., 0, 0, 0])

In [14]:
accuracy = cross_val_score(model, train_data, train_label, cv=7)
print("Accuracy: %0.2f (+/- %0.2f)" % (accuracy.mean(), accuracy.std() * 2))

Accuracy: 0.59 (+/- 0.02)


In [15]:
model.score(test_data, test_label)

0.57451612903225802

In [18]:
metrics.precision_recall_fscore_support(test_label, predict_label, beta=0.5, average=None)

/Users/hoangnguyen/miniconda3/envs/pydata/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([ 0.6152019 ,  0.        ,  0.47058824,  0.4581861 ,  0.64341085]),
 array([ 0.80310078,  0.        ,  0.14117647,  0.4581861 ,  0.42783505]),
 array([ 0.64540244,  0.        ,  0.32085561,  0.4581861 ,  0.58450704]),
 array([1290,   15,  170,  849,  776]))

In [20]:
model.predict_log_proba(test_data)

array([[-3.00227756, -3.46029522, -0.96066143, -2.22441863, -0.848315  ],
       [-5.04295879, -5.00423521, -3.34157602, -2.29059289, -0.16222684],
       [-0.33242192, -8.13627964, -5.53635687, -1.77170218, -2.22065071],
       ..., 
       [-0.45981359, -9.00071225, -5.0267962 , -1.37858216, -2.20745635],
       [-0.83432737, -7.39207737, -4.11577876, -1.95876573, -0.89680225],
       [-0.76289575, -6.28423801, -4.20211648, -1.17294361, -1.57309719]])